=== amitabha66/JLibrary01/JLibrary01/lib/Oracle/Oracle-XDK/xdk/demo/java/jaxb/Sample8/sample8.xsd
<?xml version="1.0"?>

<!-- The element declaration type is a complex type definition -->

<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://generated/sample8/"
    xmlns:po="http://generated/sample8/"
    xmlns:io="http://generated/sample8-1/"
    elementFormDefault="qualified">
  
     <xsd:import namespace="http://generated/sample8-1/"
      schemaLocation="sample8-1.xsd" />

     <xsd:complexType name="PurchaseOrderType">
       <xsd:sequence>
         <xsd:element name="shipTo" type="po:Address"/>
         <xsd:element name="billTo" type="io:USAddress"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:complexType name="Address">
       <xsd:sequence>
         <xsd:element name="name"   type="xsd:string"/>
         <xsd:element name="street" type="xsd:string"/>
         <xsd:element name="city"   type="xsd:string"/>
         <xsd:element name="state"  type="xsd:string"/>
         <xsd:element name="country" type="xsd:string"/>
         <xsd:element name="zip"    type="xsd:decimal"/>
       </xsd:sequence>
     </xsd:complexType>

     <xsd:element name="PurchaseOrder" type="po:PurchaseOrderType"/>

</xsd:schema>

=== amitabha66/JLibrary01/JLibrary01/lib/Oracle/Oracle-XDK/xdk/demo/java/jaxb/Sample8/sample8.xml
<?xml version="1.0"?>
<PurchaseOrder xmlns = "http://generated/sample8/"
           xmlns:io = "http://generated/sample8-1/"
           xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation = "http://generated/sample8/ sample8.xsd">

 <shipTo>
   <name>Alfred Hitchcock</name>
   <street>Old Francisco Road</street>
   <city>Casablanca City</city>
   <state>Casablanca</state>
   <country>Algeria</country>
   <zip>190290</zip> 
 </shipTo>

 <billTo>
   <io:name>A and B Music Company</io:name>
   <io:street>Casablanca Avenue </io:street>
   <io:city>Los Angeles City </io:city>
   <io:state>CA</io:state>
   <io:zip>95134</io:zip>
 </billTo>

</PurchaseOrder>
