=== amitabha66/JLibrary01/JLibrary01/lib/Oracle/Oracle-XDK/xdk/demo/java/jaxb/Sample5/sample5.xsd
<?xml version="1.0"?>

<schema xmlns = "http://www.w3.org/2001/XMLSchema"
            xmlns:bo="http://www.oracle.com/sample5/"
            targetNamespace="http://www.oracle.com/sample5/"
            elementFormDefault="qualified">

   <complexType name="baseType">
      <choice maxOccurs="unbounded">
         <element name="a" type="string"/>
         <element name="b" type="string"/>
         <element name="c" type="int"/>
      </choice>
   </complexType>

   <element name="base" type="bo:baseType"/>

</schema>

=== amitabha66/JLibrary01/JLibrary01/lib/Oracle/Oracle-XDK/xdk/demo/java/jaxb/Sample5/sample5.xml
<?xml version="1.0"?>
<base xmlns = "http://www.oracle.com/sample5/"
           xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation = "http://www.oracle.com/sample5/ sample5.xsd">
  <a> The element A  </a>
  <b> The element B </b>
  <c> 1 </c>
  <c> 2 </c>
  <b> The second element B </b>
  <b> The thid element B </b>
  <c> 3 </c>
  <a> The second elemnet A </a>
</base>
